apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::829250931565:role/eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - eks-console-dashboard-full-access-group
      - system:discovery
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::829250931565:role/ConfluentSEAdminRole
      username: ConfluentSEAdminRole